Consolidated generation of g_options output
Generation of all g_tool -man tex code is now in the same shell script

Change-Id: Icbb3275e7a2c4945918ac36e5d19c907eca7226e

diff --git a/mkman b/mkman
--- a/mkman
+++ b/mkman
@@ -52,13 +52,27 @@ for PROG in $PROGRAMS; do
     fi
 done
 
+INSTALLED_OPTIONS_PROGRAM_NAME=$(find $GMXBIN -name \*${OPTIONS_PROGRAM_NAME}\*)
+if [[ "x${INSTALLED_OPTIONS_PROGRAM_NAME}" == "x" ]]; then
+    echo "Error: Can't find the executable '${OPTIONS_PROGRAM_NAME}' in GMXBIN directory $GMXBIN"
+    echo "I need it to create a LaTeX file."
+    exit 1
+else
+    ${INSTALLED_OPTIONS_PROGRAM_NAME} -hidden -man tex 2> /dev/null
+fi
+
+# We don't want the section header to actually be g_options
+sed -i -e "s/${OPTIONS_PROGRAM_NAME}/options/g" ${OPTIONS_PROGRAM_NAME}.tex
+
+mv ${OPTIONS_PROGRAM_NAME}.tex ${MANDIR}/
+
 cat > ${PROGMAN}.tex << EOD
 \chapter{Manual Pages}
 \label{app:progman}
 
 {\small
 %${OPTIONS_PROGRAM_NAME}.tex is created by the GROMACS installed binary ${OPTIONS_PROGRAM_NAME}
-\input{${OPTIONS_PROGRAM_NAME}.tex}
+\input{${MANDIR}/${OPTIONS_PROGRAM_NAME}.tex}
 }
 {\small
 \input{${MANDIR}/all}
